// GENERATED by scripts/hash-assets.mjs — do not edit by hand.
// Rebuilt on every `npm run build`. Maps files in public/ to a content hash
// so lib/assets.ts can version their URLs (see asset()).
export const ASSET_HASHES: Record<string, string> = {
  "/images/artist-square.jpg": "240cfd7d",
  "/images/artist.jpg": "aec066c0",
  "/images/design-fern.jpg": "74b75612",
  "/images/design-maple.jpg": "008f411e",
  "/images/design-oak.jpg": "b0116189",
  "/images/design-sumac.jpg": "cc190962",
  "/images/detail.jpg": "98e505b0",
  "/images/fern-mark.svg": "c69b6f7a",
  "/images/fern.svg": "d1373724",
  "/images/hero-texture.jpg": "74f31c0e",
  "/images/leaf-mark.svg": "e0d0d536",
  "/images/logo-mark.png": "0b4547e4",
  "/images/logo.png": "82fa4d99",
  "/images/maple-shirt.jpg": "a35624b4",
  "/images/recent/IMG_2742.heic": "7dd1a6a5",
  "/images/recent/broadleaf-flat.jpg": "14a0688d",
  "/images/recent/fern-flat.jpg": "63af2782",
  "/images/recent/fern-worn.jpg": "66367307",
  "/images/recent/gathering-sumac.jpg": "b6ed197b",
  "/images/recent/sumac-flat.jpg": "5d93e435",
  "/images/sumac-shirt.jpg": "dbd118e0",
};
