// Walks public/ and writes lib/assetManifest.ts: every file's URL path → a short
// content hash. Runs automatically before `next build` (package.json "prebuild"),
// so a replaced photo or logo gets a new "?v=" in its URL and browsers + Vercel's
// image cache fetch the new file instead of handing back the old one.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const root = process.cwd();
const pub = join(root, "public");
const out = join(root, "lib", "assetManifest.ts");
const entries = {};

function walk(dir) {
  for (const name of readdirSync(dir)) {
    if (name.startsWith(".")) continue; // .DS_Store and friends
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) walk(full);
    else if (st.isFile()) {
      const url = "/" + relative(pub, full).split(sep).join("/");
      entries[url] = createHash("md5").update(readFileSync(full)).digest("hex").slice(0, 8);
    }
  }
}
walk(pub);

const keys = Object.keys(entries).sort();
const body = keys.map((k) => `  ${JSON.stringify(k)}: "${entries[k]}",`).join("\n");
writeFileSync(
  out,
  `// GENERATED by scripts/hash-assets.mjs — do not edit by hand.\n` +
    `// Rebuilt on every \`npm run build\`. Maps files in public/ to a content hash\n` +
    `// so lib/assets.ts can version their URLs (see asset()).\n` +
    `export const ASSET_HASHES: Record<string, string> = {\n${body}\n};\n`,
);
console.log(`hash-assets: ${keys.length} files → lib/assetManifest.ts`);
